### PR TITLE
Hotfix for script namespace issues

### PR DESCRIPTION
**Pull request by zackorenberg**
In the lab, we were having an issue with certain scripts being run. After some research and test scripts designed to recreate the error and identify the cause, I determined that it was because variable declaration would affect locals(), whereas it being called anywhere that isnt local (ex, list comprehension, function declaration) would throw a NameError. This included importing libraries (in this case, numpy).

The solution I determined was to create a copy of globals, update globals['self'] = self so that the script would continue to operate under DataTaker, and then pass the same dictionary as both locals and globals to exec, thus superficially mending this error, as when a local variable is declared within the script, it is created under the same dictionary object as globals, allowing it to be used within functions/classes/list comprehensions.

### CODE REVIEW

**Comment by zackorenberg** [comment]
The following code will reproduce the error, independent of LabGUI:


`$ python script_caller.py`

with the following files

script_caller.py:
```
class call_script(object):
    def __init__(self):
        userScriptName = 'script_to_run.py'
        script = open(userScriptName)
        code = compile(script.read(), script.name, 'exec')
        exec(code)
        script.close()

    def print_something(self):
        print("something")


call_script()
````
script_to_run.py:
```
import numpy as np

start = 1
end = 2
steps = 20
sep = (end-start)/steps

def function_to_run(values):
    print(values)
    print(np.zeros(10))
    self.print_something()

# this will recreate the import error
function_to_run('value')

# this will recreate the list comprehension local variable error
listc = [x*sep for x in range(steps)]
function_to_run(listc)
```

**Comment by zackorenberg** [comment]
The following code (which was implemented into `DataManagement.py` for this hotfix) will no longer cause the same error, and the script will execute as expected

The following code will reproduce the error, independent of LabGUI:


`$ python script_caller.py`

with the following files

script_caller.py:
```
class call_script_fixed(object):
    def __init__(self):
        userScriptName = 'script_to_run.py'
        script = open(userScriptName)
        code = compile(script.read(), script.name, 'exec')

        namespace = globals().copy()
        namespace['self'] = self

        exec(code, namespace, namespace)
        script.close()

    def print_something(self):
        print("something")


call_script_fixed()
````
script_to_run.py:
```
import numpy as np

start = 1
end = 2
steps = 20
sep = (end-start)/steps

def function_to_run(values):
    print(values)
    print(np.zeros(10))
    self.print_something()

# this will no longer recreate the import error
function_to_run('value')

# this will no longer recreate the list comprehension local variable error
listc = [x*sep for x in range(steps)]
function_to_run(listc)
```

and will have the following output:
```
value
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
something
[0.0, 0.05, 0.1, 0.15000000000000002, 0.2, 0.25, 0.30000000000000004, 0.35000000000000003, 0.4, 0.45, 0.5, 0.55, 0.6000000000000001, 0.65, 0.7000000000000001, 0.75, 0.8, 0.8500000000000001, 0.9, 0.9500000000000001]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
something
```

**Review by Bachibouzouk — APPROVED** [review]
I never worked with globals() so I am not sure this will not create errors in the future. I would add a link to this PR into the docstring for future users. I'll approve it so you can merge after you are done with your tests :)

**Comment by zackorenberg** [comment]
@Bachibouzouk it seems to work with all my tests. globals() seems to really just mean imported libraries and global variables, whereas locals() include the datataker class. When executed the way it is in DataTaker, as the script is run in the scope of a function rather than the class, normal code operates on locals(), as it is within the scope of a function, meaning any import statements solely import the functions/libraries to locals(). However, local functions within the script are not run like the rest of the code, as they only receive globals() which makes it unable to access any variables or imported functions/libraries, as well as the 'self' method. This can be problematic and would require non-intuitive programming techniques to avoid error. As well, it would not be backwards compatible with older scripts. By creating a copy of the globals() within datataker, and adding the 'self' variable, it essentially allows the script to mimic the functionality of being run as a classes function, instead of running within a class function, and it treats every global import statement as an actual global import statement. An added benefit of creating a copy of globals() is that the user is unable to unintentionally cause LabGUI to crash by renaming a preexisting variable, which without this hotfix, will persist after the script is finished running.

I am unsure of how to write this as a docstring. I did add a very detailed comment, including my justification, to LabTools.DataManagement.DataTaker.run, where the script is actually run. Please let me know how to proceed, as this is a major bug that must be fixed ASAP

**Comment by Bachibouzouk** [comment]
> I am unsure of how to write this as a docstring. I did add a very detailed comment, including my justification, to LabTools.DataManagement.DataTaker.run, where the script is actually run. Please let me know how to proceed, as this is a major bug that must be fixed ASAP

I only see one commit, did you force push your changes?

In the class which uses globals() I would simply add 
```
class call_script_fixed(object):
    """
    related to https://github.com/LabGUI/LabGUI/pull/23
    """
```
inside the docstring

**Comment by Bachibouzouk** [comment]
btw, I had already approved the PR, you could merge whenever you want :)

note : you'll have to merge develop into this branch first, fix the conflict in `.gitignore`, re-push and then merge

**Comment by zackorenberg** [comment]
@Bachibouzouk I have added the docstring you recommended and resolved the .gitignore conflict. I will merge the pull request

**Pull request merged**
