### PR TITLE
Hotfix/sim900 itc503s

### PR DESCRIPTION
**Pull request by zackorenberg**
Hotfix for both SIM900 and ITC503S, that depend on hotfix/buffer_clear branch

### CODE REVIEW

**Comment by Bachibouzouk** [comment]
@zackorenberg , you can refer to the PR of the branch --> #31

**Comment by zackorenberg** [comment]
@Bachibouzouk we should merge this into develop as soon as possible

**Comment by Bachibouzouk** [comment]
> @Bachibouzouk we should merge this into develop as soon as possible

@zackorenberg - it would be best if one of the current lab member tests the code of the PR as I can't interface with instruments :)

For instrument specific PR, you can go ahead and merge it if you tested it live. Better if someone else from the lab who's going to use it also tests it before you merge. But if they don't have the time to do so, you can take the decision to merge and fix errors in subsequent PRs :)

**Comment by zackorenberg** [comment]
Hi @Bachibouzouk, this bugfix was tested by members of the lab when the specific error had occured. Since then they have been on this branch when using SIM900 and ITC503S. This should be merged ASAP

**Comment by Bachibouzouk** [comment]
> Hi @Bachibouzouk, this bugfix was tested by members of the lab when the specific error had occured. Since then they have been on this branch when using SIM900 and ITC503S. This should be merged ASAP

@taliamo or @mateiu2003k cannot approve your pull requests @zackorenberg ?

**Review by Bachibouzouk — APPROVED** [review]

**Pull request merged**
